<?php
	const PACKET_DISCONNECT = -1;
	const PACKET_AUTH = 0;
	const PACKET_LIST = 1;
	const PACKET_SELECT = 5;
	const PACKET_DISCONNECT_CLIENT = 10;
	const PACKET_LISTCOUNTRIES = 12;
	const PACKET_LISTOPERATINGSYSTEMS = 13;
	const PACKET_LISTOFFLINE = 14;
	const PACKET_REMOVE_OFFLINE = 15;
?>